# Generated by Django 3.0.6 on 2020-05-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frip', '0002_auto_20200517_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frip',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
