# Generated by Django 3.0.6 on 2020-05-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frip', '0003_auto_20200517_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frip',
            name='dateValidFrom',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='frip',
            name='dateValidTo',
            field=models.DateTimeField(null=True),
        ),
    ]
