# Generated by Django 3.0.6 on 2020-05-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frip', '0004_auto_20200517_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frip',
            name='faked_price',
            field=models.IntegerField(null=True),
        ),
    ]
