# Generated by Django 3.0.6 on 2020-05-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frip', '0008_auto_20200517_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frip',
            name='faked_price',
            field=models.IntegerField(null=True),
        ),
    ]
