# Generated by Django 3.0.6 on 2020-05-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frip', '0011_auto_20200518_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childoption',
            name='base_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childoption',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='base_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
