# Generated by Django 3.0.6 on 2020-05-18 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frip', '0012_auto_20200518_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childoption',
            name='option_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frip.OptionType'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frip.OptionType'),
        ),
    ]
